controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: forward_command_controller/ForwardCommandController

effort_controller:
  ros__parameters:
    joints:
      - test_motor_joint
    interface_name: effort
